server:
  port: 8080

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

default:
  ribbon:
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 2
    OkToRetryOnAllOperations: true // All operations should be idempotent

logging:
  path: /var/log
  level:
    root: INFO
    com:
      ongo360:
        demo: DEBUG

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/zipkin?autoReconnect=true
    username: zipkin
    password: zipkin
    driver-class-name: com.mysql.jdbc.Driver
  sleuth:
    enabled: false

zipkin:
  storage:
    type: mysql
