server:
  port: 8761

spring:
  application:
    name: eureka
  profiles:
    active: dev
  instance:
    hostname: localhost
    preferIpAddress: true

endpoints:
  shutdown:
    sensitive: false
    enabled: true



logging:
  path: /var/log/omega-framework
  level:
    root: info
    com:
      omega:
        framework: DEBUG
---
spring:
  profiles: dev
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


---
spring:
  profiles: eureka1
eureka:
  #instance:
  #  hostname: localhost
  #  preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka2.instance.hostname}:${server.port}/eureka/,http://${eureka3.instance.hostname}:${server.port}/eureka/


---
spring:
  profiles: eureka2
eureka:
  #instance:
    #hostname: localhost
  #  preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka1.instance.hostname}:${server.port}/eureka/,http://${eureka3.instance.hostname}:${server.port}/eureka/


---
spring:
  profiles: eureka3
eureka:
  #instance:
    #hostname: localhost
  #  preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka1.instance.hostname}:${server.port}/eureka/,http://${eureka2.instance.hostname}:${server.port}/eureka/
