server:
  port: 8887

spring:
  application:
    name: omega-framework-configserver
  profiles:
    active: native #配置文件的profile，要跟配置文件当前使用的profile相符
  rabbitmq:
    host: localhost
    port: 5672
    username: ongo360
    password: ongo360
    virtual-host: ongo360_vhost
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        encrypt:
          enabled: false

endpoints:
  shutdown:
    sensitive: false
    enabled: true

logging:
  path: /var/log/omega-framework
  level:
    root: info
    com:
      omega:
        framework: DEBUG
